// Writes docs/api-contract.md: the REST contract the laboratory backend must
// implement, read from src/services/http/endpoints.ts (method and path) and
// the TypeScript types (arguments and the DTO each call returns).
//
//   npm run contract

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const configPath = resolve(root, 'tsconfig.app.json')
const config = ts.getParsedCommandLineOfConfigFile(
  configPath,
  {},
  {
    ...ts.sys,
    onUnRecoverableConfigFileDiagnostic: (d) => {
      throw new Error(ts.flattenDiagnosticMessageText(d.messageText, '\n'))
    },
  },
)
const program = ts.createProgram(config.fileNames, config.options)
const checker = program.getTypeChecker()
const endpointsFile = program.getSourceFile(
  resolve(root, 'src/services/http/endpoints.ts'),
)
if (!endpointsFile) throw new Error('endpoints.ts not found')

/** The ENDPOINTS object literal. */
let table
ts.forEachChild(endpointsFile, (node) => {
  if (!ts.isVariableStatement(node)) return
  for (const decl of node.declarationList.declarations)
    if (decl.name.getText() === 'ENDPOINTS') table = decl.initializer
})
if (!table || !ts.isObjectLiteralExpression(table))
  throw new Error('ENDPOINTS not found')

const contractFile = program.getSourceFile(
  resolve(root, 'src/services/contract.ts'),
)
const labApiAlias = contractFile.statements.find(
  (s) => ts.isTypeAliasDeclaration(s) && s.name.text === 'LabApi',
)
const labApi = checker.getTypeAtLocation(labApiAlias.name)

const typeText = (type) =>
  checker
    .typeToString(type, undefined, ts.TypeFormatFlags.NoTruncation)
    .replace(/import\("[^"]+"\)\./g, '')
    .replace(/\|/g, '\\|')

function signature(ns, method) {
  const nsType = checker.getTypeOfSymbol(labApi.getProperty(ns))
  const fn = checker.getTypeOfSymbol(nsType.getProperty(method))
  const sig = fn.getCallSignatures()[0]
  const params = sig
    .getParameters()
    .map((p) => {
      const decl = p.valueDeclaration
      const optional = decl && ts.isParameter(decl) && decl.questionToken
      return `${p.name}${optional ? '?' : ''}: ${typeText(checker.getTypeOfSymbol(p))}`
    })
    .join(', ')
  let returns = sig.getReturnType()
  const awaited = checker.getAwaitedType(returns)
  if (awaited) returns = awaited
  return { params, returns: typeText(returns) }
}

const lines = [
  '# Laboratory API contract',
  '',
  'Generated by `npm run contract` from `src/services/http/endpoints.ts` and the TypeScript types. Do not edit by hand.',
  '',
  'Conventions:',
  '',
  '- Every path is under the API base (`VITE_API_BASE_URL`, default `/api`) and versioned `/v1`.',
  '- The browser sends the session cookie; the server authenticates and authorises every call. The frontend never makes trust decisions.',
  '- GET filters are query parameters (arrays repeat the key, nested objects are JSON). Writes send a JSON body and an `Idempotency-Key` header; every request carries `X-Request-Id`.',
  '- Responses are the DTOs named below (`src/mock/api/types.ts`); times are epoch milliseconds.',
  '- Errors: an HTTP status and `{ "code": ErrorCode, "params": {...}, "requestId": "..." }`, where `code` is one of `ERROR_CODES` in `src/domain/errors.ts` (shown to the user in their language).',
  '- Each write enforces the same permission, workflow and audit rules as `src/mock/engine/` (see README, "Backend seam").',
  '',
]

for (const nsProp of table.properties) {
  const ns = nsProp.name.getText()
  lines.push(
    `## ${ns}`,
    '',
    '| Call | HTTP | Arguments | Returns |',
    '|---|---|---|---|',
  )
  for (const mProp of nsProp.initializer.properties) {
    const method = mProp.name.getText()
    const call = mProp.initializer
    const verb = call.expression
      .getText()
      .toUpperCase()
      .replace('DEL', 'DELETE')
    const path = call.arguments[0].text
    const { params, returns } = signature(ns, method)
    lines.push(
      `| \`${ns}.${method}\` | \`${verb} ${path}\` | ${params ? `\`${params}\`` : 'none'} | \`${returns}\` |`,
    )
  }
  lines.push('')
}

const out = resolve(root, 'docs/api-contract.md')
mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, lines.join('\n'))
console.log(`Wrote ${out}`)
